spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: keep
      port: 27017
      host: localhost
      auto-index-creation: true

logging:
  file:
    path: /
    name: log.txt
  level:
    root: INFO